### README

From coord, get features needed for ML prediction.

### Requirements

In [ ]:
# Python libraries
"""
biopython==1.85
pandas==2.2.3
"""

# Outer softwares
"""
SVM-BPfinder-3M: Corvelo A, Hallegger M, Smith CW, Eyras E. Genome-wide association between branch point properties and alternative splicing. PLoS Comput Biol. 2010 Nov 24;6(11):e1001016. doi: 10.1371/journal.pcbi.1001016. PMID: 21124863; PMCID: PMC2991248.
maxentscan: Yeo G, Burge CB. Maximum entropy modeling of short sequence motifs with applications to RNA splicing signals. J Comput Biol. 2004;11(2-3):377-94. doi: 10.1089/1066527041410418. PMID: 15285897.
"""

'\npandas==2.2.3\nbiopython==1.85\n'

In [ ]:
# Import libraries
import pandas as pd
import subprocess
import io
import tempfile
import os


# Outer softwares
bpfinder = '/PATH/TO/SVM-BPfinder-3M/svm_bpfinder.py'
maxentscan = '/PATH/TO/maxEntScan/fordownload'

### Constants

In [ ]:
# Input: path to file with sequence of minigenes
SEQ_PATH = '/PATH/TO/Minigene_list.xlsx' 
INTRON_COL = 'intron'
DNEXON_COL = 'downstream exon'

# Output: set directory
OUTPUT_DIR = '/PATH/TO/OUTPUT'
OUTPUT_PREFIX = 'minigene'

### Functions

In [4]:
# CALCULATE SPLICE SITE SCORES

def maxentscan_score_3ss(sequences):
    
    # Create a temp file for input sequences
    with tempfile.NamedTemporaryFile(mode='w+', delete=False) as temp_input:
        for seq in sequences:
            temp_input.write(seq + '\n')
        temp_input_name = temp_input.name

    try:
        script_path = os.path.join(maxentscan, 'score3.pl')

        # Run score3.pl from maxentscan_dir to ensure matrix files found
        result = subprocess.run(
            ['perl', script_path, temp_input_name],
            cwd=maxentscan,
            capture_output=True,
            text=True,
            check=True
        )

        # Parse scores: each line is "<sequence>\t<score>"
        scores = [float(line.strip().split('\t')[1]) for line in result.stdout.strip().split('\n')]

    finally:
        # Clean up temp file
        os.remove(temp_input_name)

    return scores

In [5]:
# CALCULATE BRANCH POINT SCORES

# writes a fasta file with intron sequece, each intron is an identifier
def write_fasta(seq_dict, fasta_filename, trim=(0,0)):
    # trim: number of bases do remove from 5' and 3' end
    start_trim, end_trim = trim

    with open(fasta_filename, "w") as fasta_file:
        for intron_id, seq in seq_dict.items():
            seq = str(seq)
            
            # ignore seq shorter that trim
            if len(seq) <= start_trim + end_trim:
                continue
            
            trimmed_seq = seq[start_trim:-end_trim] if end_trim > 0 else seq[start_trim:]
            fasta_file.write(f">{intron_id}\n{trimmed_seq}\n")

# get BPfinder output from fasta file
# output is a dataframe showing only the best prediction of BP per intron
def find_bp(fasta_filename):
    
    # Run SVM-BPfinder
    cmd = f"{bpfinder} -i {fasta_filename} -s Hsap -l 100 -d 10"
    result = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    
    # Check for errors
    if result.returncode != 0:
        print("Error running SVM-BPfinder:", result.stderr)
        return None

    # Convert output into a DataFrame
    svm_output = pd.read_csv(io.StringIO(result.stdout), sep="\t")
    
    # Ensure `svm_scr` is numeric
    svm_output["svm_scr"] = pd.to_numeric(svm_output["svm_scr"], errors="coerce")

    # Select the row with the highest `svm_scr` for each intron
    svm_output_best = svm_output.loc[svm_output.groupby("seq_id")["svm_scr"].idxmax()]
    
    return svm_output_best

### Analysis

##### 1. Read input files

In [ ]:
# sequence table
data_df = pd.read_csv(SEQ_PATH)

# select only NAGNAG
data_df = data_df[data_df['NNAGNAG type'] != 'no NAGNAG'].copy()
data_df

,name,backbone,sequence complete,upstream exon,intron,downstream exon,NNAGNAG type,PSI ctrl. (s1),PSI ctrl. (s2),PSI ctrl. (s3),...,PSI ctrl. (s6),PSI FAM32AD17 (s1),PSI FAM32AD17 (s2),PSI FAM32AD17 (s3),PSI FAM32AD17 (s4),PSI FAM32AD17 (s5),PSI FAM32AD17 (s6),mean delta PSI,regulated (true/false) dPSI>15%,position mutation (AG gain)
0,ppp1r12c CAGCAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,CCAGCAG,64.04,68.57,65.51,...,NaN,27.96,28.83,27.89,NaN,NaN,NaN,37.81,True,na
1,gpank1 CAGCAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,CCAGCAG,72.31,73.20,71.15,...,NaN,36.70,36.92,36.87,NaN,NaN,NaN,35.39,True,na
2,acin1 CAGCAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,ACAGCAG,65.57,71.78,67.65,...,NaN,54.66,55.62,57.41,NaN,NaN,NaN,12.44,False,na
3,ankrd11 AAGCAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,GAAGCAG,66.78,66.22,68.59,...,NaN,53.71,47.53,51.83,NaN,NaN,NaN,16.17,True,na
4,ppp1r12c CAGCAG,pcDNA3,GACGGATCGGGAGATCTCCCGATCCCCTATGGTGCACTCTCAGTAC...,AACCACCCCCTGCAGAACCCAGAACCCTCAATGGCGTCTCCTCCCC...,gtgagtggatgccctgagaggtcctgtgaggctgggagggcccgga...,CTTGAAGAGGCCCCCTTCTCCAGGCGCTTTGGCCTCCTGAAGACAG...,CCAGCAG,65.04,62.39,55.11,...,NaN,16.41,12.03,19.85,16.14,NaN,NaN,36.27,True,na
5,ppp1r12c UAGUAG,pcDNA3,GACGGATCGGGAGATCTCCCGATCCCCTATGGTGCACTCTCAGTAC...,AACCACCCCCTGCAGAACCCAGAACCCTCAATGGCGTCTCCTCCCC...,gtgagtggatgccctgagaggtcctgtgaggctgggagggcccgga...,CTTGAAGAGGCCCCCTTCTCCAGGCGCTTTGGCCTCCTGAAGACAG...,CTAGTAG,59.14,61.24,57.41,...,NaN,26.18,21.61,21.38,24.34,NaN,NaN,38.02,True,na
6,ppp1r12c CAGAAG,pcDNA3,GACGGATCGGGAGATCTCCCGATCCCCTATGGTGCACTCTCAGTAC...,AACCACCCCCTGCAGAACCCAGAACCCTCAATGGCGTCTCCTCCCC...,gtgagtggatgccctgagaggtcctgtgaggctgggagggcccgga...,CTTGAAGAGGCCCCCTTCTCCAGGCGCTTTGGCCTCCTGAAGACAG...,CCAGAAG,86.88,83.07,81.34,...,NaN,69.29,70.66,67.23,66.39,NaN,NaN,13.66,False,na
7,ppp1r12c AAGCAG,pcDNA3,GACGGATCGGGAGATCTCCCGATCCCCTATGGTGCACTCTCAGTAC...,AACCACCCCCTGCAGAACCCAGAACCCTCAATGGCGTCTCCTCCCC...,gtgagtggatgccctgagaggtcctgtgaggctgggagggcccgga...,CTTGAAGAGGCCCCCTTCTCCAGGCGCTTTGGCCTCCTGAAGACAG...,CAAGCAG,19.60,23.06,14.17,...,NaN,2.77,0.00,1.35,1.47,NaN,NaN,17.43,True,na
9,ppp1r12c UAGCAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,CTAGCAG,65.74,69.00,NaN,...,NaN,32.25,42.45,NaN,NaN,NaN,NaN,30.02,True,na
10,ppp1r12c CAGUAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,CCAGTAG,80.91,78.51,NaN,...,NaN,53.68,61.64,NaN,NaN,NaN,NaN,22.05,True,na
11,ppp1r12c AAGCAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,CAAGCAG,19.19,17.87,NaN,...,NaN,0.00,1.90,NaN,NaN,NaN,NaN,17.58,True,na
12,ppp1r12c CAGAAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,CCAGAAG,100.00,100.00,NaN,...,NaN,100.00,99.97,NaN,NaN,NaN,NaN,0.02,False,na
13,ppp1r12c GCAGCAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,GCAGCAG,100.00,99.73,NaN,...,NaN,100.00,96.10,NaN,NaN,NaN,NaN,1.82,False,na
14,ppp1r12c UCAGCAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,TCAGCAG,84.66,79.60,NaN,...,NaN,65.22,57.96,NaN,NaN,NaN,NaN,20.54,True,na
15,ppp1r12c AAAGCAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,AAAGCAG,60.32,55.80,NaN,...,NaN,31.93,36.11,NaN,NaN,NaN,NaN,24.04,True,na
16,ppp1r12c ACAGAAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,ACAGAAG,100.00,100.00,NaN,...,NaN,100.00,100.00,NaN,NaN,NaN,NaN,0.00,False,na
18,irf7 AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,CTGGAACCCGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGGA...,CTAGCAG,83.02,72.35,74.59,...,76.0,39.22,40.86,36.28,36.00,43.0,29.0,37.27,True,612805
20,ocrl AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,GAGGACCTGGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGGA...,TTAGTAG,100.00,100.00,99.71,...,100.0,100.00,91.10,91.34,100.00,100.0,100.0,2.88,False,128722151
21,brca1 WT (?),GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,GAAGCAG,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,na
22,brca1 stop-gain,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,GAAGTAG,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,na
23,cftr stop-gain,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,TCAGTAG,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,na
25,scn8a AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,GTGGTGGTGAGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGG...,AAAGCAG,77.40,77.99,78.03,...,NaN,27.69,26.03,26.78,NaN,NaN,NaN,50.97,True,52180321
26,kcnq1 AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,CTTCCTCATCGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGG...,CTAGCAG,39.54,44.16,45.32,...,NaN,79.78,81.47,76.70,NaN,NaN,NaN,-36.31,True,2549153
28,prpf8 AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,GGCCCTGTAGGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGG...,ATAGTAG,91.74,93.19,90.26,...,NaN,73.12,78.29,81.58,NaN,NaN,NaN,14.07,False,1580993
30,ccdc171 AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,GCTAAGAAGCGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGG...,TTAGAAG,100.00,100.00,100.00,...,NaN,100.00,100.00,100.00,NaN,NaN,NaN,0.00,False,15695229
31,ift172 AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,GAGCTGGAGGGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGG...,CCAGCAG,94.37,100.00,93.21,...,NaN,62.89,65.22,64.29,NaN,NaN,NaN,31.73,True,27680627
33,bltp1 AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,GTTGGTTCCTGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGG...,CTAGCAG,19.39,21.78,24.11,...,NaN,13.78,16.57,20.71,NaN,NaN,NaN,4.74,False,123210237
35,adck3 AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,TACCCTGGCGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGGA...,ACAGTAG,100.00,100.00,100.00,...,NaN,100.00,100.00,100.00,100.00,100.0,NaN,0.00,False,227171250
37,atrn AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,GACCATTCTTGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGG...,TCAGAAG,100.00,100.00,100.00,...,NaN,100.00,100.00,100.00,NaN,NaN,NaN,0.00,False,3543852
39,card9 AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,GTGTGCTCCTGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGG...,CCAGCAG,0.00,0.00,0.00,...,NaN,0.00,0.00,0.00,NaN,NaN,NaN,0.00,False,139265918
41,haghl AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,TTCGGGGCCAGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGG...,GCAGCAG,100.00,100.00,100.00,...,NaN,100.00,100.00,100.00,NaN,NaN,NaN,0.00,False,778311
43,col11a2 AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,GAGCAGACAGGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGG...,TGAGAAG,5.52,2.48,1.16,...,NaN,10.22,11.51,16.65,NaN,NaN,NaN,-9.74,False,33152106
44,dis3l2 stop-gain,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,CGAGTAG,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,na
45,fktn stop-gain,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,GTAGTAG,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,na
46,pkd1 stop-gain,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,TCAGTAG,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,na
47,scn1a stop-gain,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,ATAGTAG,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,na
48,vps13p stop-gain,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,CCAGTAG,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,na

##### 2. Get features: 3' end sequence

In [ ]:
# dictionary with intron seq + 5nt dw exon
seq_dict = (
    data_df[INTRON_COL] + data_df[DNEXON_COL].str[:5]
).to_dict()



# add seq information to the dataframe
for i in range(-15,-8):  # intronic part of the 3' end
    col_name = f"3end_{i+8}_base"  
    data_df[col_name] = data_df.index.map(
        lambda idx: str(seq_dict[idx])[i] if idx in seq_dict and len(str(seq_dict[idx])) > i else None
    )

for i in range(-8,0):  # exonic part of the 3' end
    col_name = f"3end_{i+9}_base"  
    data_df[col_name] = data_df.index.map(
        lambda idx: str(seq_dict[idx])[i] if idx in seq_dict and len(str(seq_dict[idx])) > i else None
    )

data_df

,name,backbone,sequence complete,upstream exon,intron,downstream exon,NNAGNAG type,PSI ctrl. (s1),PSI ctrl. (s2),PSI ctrl. (s3),...,3end_-2_base,3end_-1_base,3end_1_base,3end_2_base,3end_3_base,3end_4_base,3end_5_base,3end_6_base,3end_7_base,3end_8_base
0,ppp1r12c CAGCAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,CCAGCAG,64.04,68.57,65.51,...,a,g,c,a,g,G,A,G,C,G
1,gpank1 CAGCAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,CCAGCAG,72.31,73.20,71.15,...,a,g,c,a,g,G,A,G,C,G
2,acin1 CAGCAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,ACAGCAG,65.57,71.78,67.65,...,a,g,c,a,g,G,A,G,C,G
3,ankrd11 AAGCAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,GAAGCAG,66.78,66.22,68.59,...,a,g,c,a,g,G,A,G,C,G
4,ppp1r12c CAGCAG,pcDNA3,GACGGATCGGGAGATCTCCCGATCCCCTATGGTGCACTCTCAGTAC...,AACCACCCCCTGCAGAACCCAGAACCCTCAATGGCGTCTCCTCCCC...,gtgagtggatgccctgagaggtcctgtgaggctgggagggcccgga...,CTTGAAGAGGCCCCCTTCTCCAGGCGCTTTGGCCTCCTGAAGACAG...,CCAGCAG,65.04,62.39,55.11,...,a,g,c,a,g,C,T,T,G,A
5,ppp1r12c UAGUAG,pcDNA3,GACGGATCGGGAGATCTCCCGATCCCCTATGGTGCACTCTCAGTAC...,AACCACCCCCTGCAGAACCCAGAACCCTCAATGGCGTCTCCTCCCC...,gtgagtggatgccctgagaggtcctgtgaggctgggagggcccgga...,CTTGAAGAGGCCCCCTTCTCCAGGCGCTTTGGCCTCCTGAAGACAG...,CTAGTAG,59.14,61.24,57.41,...,a,g,u,a,g,C,T,T,G,A
6,ppp1r12c CAGAAG,pcDNA3,GACGGATCGGGAGATCTCCCGATCCCCTATGGTGCACTCTCAGTAC...,AACCACCCCCTGCAGAACCCAGAACCCTCAATGGCGTCTCCTCCCC...,gtgagtggatgccctgagaggtcctgtgaggctgggagggcccgga...,CTTGAAGAGGCCCCCTTCTCCAGGCGCTTTGGCCTCCTGAAGACAG...,CCAGAAG,86.88,83.07,81.34,...,a,g,a,a,g,C,T,T,G,A
7,ppp1r12c AAGCAG,pcDNA3,GACGGATCGGGAGATCTCCCGATCCCCTATGGTGCACTCTCAGTAC...,AACCACCCCCTGCAGAACCCAGAACCCTCAATGGCGTCTCCTCCCC...,gtgagtggatgccctgagaggtcctgtgaggctgggagggcccgga...,CTTGAAGAGGCCCCCTTCTCCAGGCGCTTTGGCCTCCTGAAGACAG...,CAAGCAG,19.60,23.06,14.17,...,a,g,c,a,g,C,T,T,G,A
9,ppp1r12c UAGCAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,CTAGCAG,65.74,69.00,NaN,...,a,g,c,a,g,G,A,G,C,G
10,ppp1r12c CAGUAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,CCAGTAG,80.91,78.51,NaN,...,a,g,t,a,g,G,A,G,C,G
11,ppp1r12c AAGCAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,CAAGCAG,19.19,17.87,NaN,...,a,g,c,a,g,G,A,G,C,G
12,ppp1r12c CAGAAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,CCAGAAG,100.00,100.00,NaN,...,a,g,a,a,g,G,A,G,C,G
13,ppp1r12c GCAGCAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,GCAGCAG,100.00,99.73,NaN,...,a,g,c,a,g,G,A,G,C,G
14,ppp1r12c UCAGCAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,TCAGCAG,84.66,79.60,NaN,...,a,g,c,a,g,G,A,G,C,G
15,ppp1r12c AAAGCAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,AAAGCAG,60.32,55.80,NaN,...,a,g,c,a,g,G,A,G,C,G
16,ppp1r12c ACAGAAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,ACAGAAG,100.00,100.00,NaN,...,a,g,a,a,g,G,A,G,C,G
18,irf7 AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,CTGGAACCCGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGGA...,CTAGCAG,83.02,72.35,74.59,...,a,g,c,a,g,C,T,G,G,A
20,ocrl AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,GAGGACCTGGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGGA...,TTAGTAG,100.00,100.00,99.71,...,a,g,t,a,g,G,A,G,G,A
21,brca1 WT (?),GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,GAAGCAG,NaN,NaN,NaN,...,a,g,c,a,g,G,A,G,C,G
22,brca1 stop-gain,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,GAAGTAG,NaN,NaN,NaN,...,a,g,t,a,g,G,A,G,C,G
23,cftr stop-gain,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,TCAGTAG,NaN,NaN,NaN,...,a,g,t,a,g,G,A,G,C,G
25,scn8a AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,GTGGTGGTGAGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGG...,AAAGCAG,77.40,77.99,78.03,...,a,g,c,a,g,G,T,G,G,T
26,kcnq1 AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,CTTCCTCATCGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGG...,CTAGCAG,39.54,44.16,45.32,...,a,g,c,a,g,C,T,T,C,C
28,prpf8 AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,GGCCCTGTAGGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGG...,ATAGTAG,91.74,93.19,90.26,...,a,g,t,a,g,G,G,C,C,C
30,ccdc171 AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,GCTAAGAAGCGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGG...,TTAGAAG,100.00,100.00,100.00,...,a,g,a,a,g,G,C,T,A,A
31,ift172 AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,GAGCTGGAGGGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGG...,CCAGCAG,94.37,100.00,93.21,...,a,g,c,a,g,G,A,G,C,T
33,bltp1 AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,GTTGGTTCCTGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGG...,CTAGCAG,19.39,21.78,24.11,...,a,g,c,a,g,G,T,T,G,G
35,adck3 AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,TACCCTGGCGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGGA...,ACAGTAG,100.00,100.00,100.00,...,a,g,t,a,g,T,A,C,C,C
37,atrn AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,GACCATTCTTGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGG...,TCAGAAG,100.00,100.00,100.00,...,a,g,a,a,g,G,A,C,C,A
39,card9 AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,GTGTGCTCCTGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGG...,CCAGCAG,0.00,0.00,0.00,...,a,g,c,a,g,G,T,G,T,G
41,haghl AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,TTCGGGGCCAGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGG...,GCAGCAG,100.00,100.00,100.00,...,a,g,c,a,g,T,T,C,G,G
43,col11a2 AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,GAGCAGACAGGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGG...,TGAGAAG,5.52,2.48,1.16,...,a,g,a,a,g,G,A,G,C,A
44,dis3l2 stop-gain,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,CGAGTAG,NaN,NaN,NaN,...,a,g,t,a,g,G,A,G,C,G
45,fktn stop-gain,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,GTAGTAG,NaN,NaN,NaN,...,a,g,t,a,g,G,A,G,C,G
46,pkd1 stop-gain,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,TCAGTAG,NaN,NaN,NaN,...,a,g,t,a,g,G,A,G,C,G
47,scn1a stop-gain,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,ATAGTAG,NaN,NaN,NaN,...,a,g,t,a,g,G,A,G,C,G
48,vps13p stop-gain,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,CCAGTAG,NaN,NaN,NaN,...,a,g,t,a,g,G,A,G,C,G

##### 3. Get features: splice site scores

In [9]:
# get list of proximal and distal 3'ss for stregth analysis (20nt intron + 3nt exon)
proximal_3ss_list = data_df.index.map(lambda idx: (seq_dict[idx][-28:-5]) if idx in seq_dict else None)
distal_3ss_list = data_df.index.map(lambda idx: (seq_dict[idx][-25:-2]) if idx in seq_dict else None)

#calculate maxentscan scores
data_df['proximal_3ss_score'] = maxentscan_score_3ss(proximal_3ss_list)
data_df['distal_3ss_score'] = maxentscan_score_3ss(distal_3ss_list)

data_df

,name,backbone,sequence complete,upstream exon,intron,downstream exon,NNAGNAG type,PSI ctrl. (s1),PSI ctrl. (s2),PSI ctrl. (s3),...,3end_1_base,3end_2_base,3end_3_base,3end_4_base,3end_5_base,3end_6_base,3end_7_base,3end_8_base,proximal_3ss_score,distal_3ss_score
0,ppp1r12c CAGCAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,CCAGCAG,64.04,68.57,65.51,...,c,a,g,G,A,G,C,G,5.97,10.49
1,gpank1 CAGCAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,CCAGCAG,72.31,73.20,71.15,...,c,a,g,G,A,G,C,G,6.17,8.95
2,acin1 CAGCAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,ACAGCAG,65.57,71.78,67.65,...,c,a,g,G,A,G,C,G,2.18,-1.58
3,ankrd11 AAGCAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,GAAGCAG,66.78,66.22,68.59,...,c,a,g,G,A,G,C,G,7.88,6.71
4,ppp1r12c CAGCAG,pcDNA3,GACGGATCGGGAGATCTCCCGATCCCCTATGGTGCACTCTCAGTAC...,AACCACCCCCTGCAGAACCCAGAACCCTCAATGGCGTCTCCTCCCC...,gtgagtggatgccctgagaggtcctgtgaggctgggagggcccgga...,CTTGAAGAGGCCCCCTTCTCCAGGCGCTTTGGCCTCCTGAAGACAG...,CCAGCAG,65.04,62.39,55.11,...,c,a,g,C,T,T,G,A,5.97,9.21
5,ppp1r12c UAGUAG,pcDNA3,GACGGATCGGGAGATCTCCCGATCCCCTATGGTGCACTCTCAGTAC...,AACCACCCCCTGCAGAACCCAGAACCCTCAATGGCGTCTCCTCCCC...,gtgagtggatgccctgagaggtcctgtgaggctgggagggcccgga...,CTTGAAGAGGCCCCCTTCTCCAGGCGCTTTGGCCTCCTGAAGACAG...,CTAGTAG,59.14,61.24,57.41,...,u,a,g,C,T,T,G,A,2.76,4.36
6,ppp1r12c CAGAAG,pcDNA3,GACGGATCGGGAGATCTCCCGATCCCCTATGGTGCACTCTCAGTAC...,AACCACCCCCTGCAGAACCCAGAACCCTCAATGGCGTCTCCTCCCC...,gtgagtggatgccctgagaggtcctgtgaggctgggagggcccgga...,CTTGAAGAGGCCCCCTTCTCCAGGCGCTTTGGCCTCCTGAAGACAG...,CCAGAAG,86.88,83.07,81.34,...,a,a,g,C,T,T,G,A,7.20,5.06
7,ppp1r12c AAGCAG,pcDNA3,GACGGATCGGGAGATCTCCCGATCCCCTATGGTGCACTCTCAGTAC...,AACCACCCCCTGCAGAACCCAGAACCCTCAATGGCGTCTCCTCCCC...,gtgagtggatgccctgagaggtcctgtgaggctgggagggcccgga...,CTTGAAGAGGCCCCCTTCTCCAGGCGCTTTGGCCTCCTGAAGACAG...,CAAGCAG,19.60,23.06,14.17,...,c,a,g,C,T,T,G,A,2.59,8.12
9,ppp1r12c UAGCAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,CTAGCAG,65.74,69.00,NaN,...,c,a,g,G,A,G,C,G,5.62,9.63
10,ppp1r12c CAGUAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,CCAGTAG,80.91,78.51,NaN,...,t,a,g,G,A,G,C,G,5.75,9.16
11,ppp1r12c AAGCAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,CAAGCAG,19.19,17.87,NaN,...,c,a,g,G,A,G,C,G,2.59,9.27
12,ppp1r12c CAGAAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,CCAGAAG,100.00,100.00,NaN,...,a,a,g,G,A,G,C,G,7.20,5.56
13,ppp1r12c GCAGCAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,GCAGCAG,100.00,99.73,NaN,...,c,a,g,G,A,G,C,G,7.26,7.46
14,ppp1r12c UCAGCAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,TCAGCAG,84.66,79.60,NaN,...,c,a,g,G,A,G,C,G,5.71,10.33
15,ppp1r12c AAAGCAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,AAAGCAG,60.32,55.80,NaN,...,c,a,g,G,A,G,C,G,3.65,7.37
16,ppp1r12c ACAGAAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,ACAGAAG,100.00,100.00,NaN,...,a,a,g,G,A,G,C,G,7.74,3.21
18,irf7 AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,CTGGAACCCGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGGA...,CTAGCAG,83.02,72.35,74.59,...,c,a,g,C,T,G,G,A,1.92,6.52
20,ocrl AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,GAGGACCTGGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGGA...,TTAGTAG,100.00,100.00,99.71,...,t,a,g,G,A,G,G,A,4.69,4.44
21,brca1 WT (?),GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,GAAGCAG,NaN,NaN,NaN,...,c,a,g,G,A,G,C,G,4.57,4.20
22,brca1 stop-gain,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,GAAGTAG,NaN,NaN,NaN,...,t,a,g,G,A,G,C,G,2.68,3.69
23,cftr stop-gain,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,TCAGTAG,NaN,NaN,NaN,...,t,a,g,G,A,G,C,G,3.86,3.60
25,scn8a AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,GTGGTGGTGAGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGG...,AAAGCAG,77.40,77.99,78.03,...,c,a,g,G,T,G,G,T,2.13,5.96
26,kcnq1 AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,CTTCCTCATCGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGG...,CTAGCAG,39.54,44.16,45.32,...,c,a,g,C,T,T,C,C,7.62,6.01
28,prpf8 AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,GGCCCTGTAGGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGG...,ATAGTAG,91.74,93.19,90.26,...,t,a,g,G,G,C,C,C,2.45,-0.09
30,ccdc171 AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,GCTAAGAAGCGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGG...,TTAGAAG,100.00,100.00,100.00,...,a,a,g,G,C,T,A,A,4.98,3.00
31,ift172 AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,GAGCTGGAGGGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGG...,CCAGCAG,94.37,100.00,93.21,...,c,a,g,G,A,G,C,T,7.75,5.65
33,bltp1 AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,GTTGGTTCCTGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGG...,CTAGCAG,19.39,21.78,24.11,...,c,a,g,G,T,T,G,G,3.10,5.77
35,adck3 AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,TACCCTGGCGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGGA...,ACAGTAG,100.00,100.00,100.00,...,t,a,g,T,A,C,C,C,5.07,-0.28
37,atrn AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,GACCATTCTTGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGG...,TCAGAAG,100.00,100.00,100.00,...,a,a,g,G,A,C,C,A,1.68,-1.96
39,card9 AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,GTGTGCTCCTGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGG...,CCAGCAG,0.00,0.00,0.00,...,c,a,g,G,T,G,T,G,0.22,3.02
41,haghl AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,TTCGGGGCCAGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGG...,GCAGCAG,100.00,100.00,100.00,...,c,a,g,T,T,C,G,G,7.69,3.07
43,col11a2 AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,GAGCAGACAGGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGG...,TGAGAAG,5.52,2.48,1.16,...,a,a,g,G,A,G,C,A,-0.84,3.03
44,dis3l2 stop-gain,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,CGAGTAG,NaN,NaN,NaN,...,t,a,g,G,A,G,C,G,-5.06,5.99
45,fktn stop-gain,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,GTAGTAG,NaN,NaN,NaN,...,t,a,g,G,A,G,C,G,3.31,2.39
46,pkd1 stop-gain,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,TCAGTAG,NaN,NaN,NaN,...,t,a,g,G,A,G,C,G,0.14,4.93
47,scn1a stop-gain,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,ATAGTAG,NaN,NaN,NaN,...,t,a,g,G,A,G,C,G,4.43,2.23
48,vps13p stop-gain,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,CCAGTAG,NaN,NaN,NaN,...,t,a,g,G,A,G,C,G,9.67,8.06

##### 4. Get features: branchpoint

In [10]:
# Write separate FASTA files for short and long introns
write_fasta(seq_dict, "short_introns.fa", trim=(0, 8))
write_fasta(seq_dict, "long_introns.fa", trim=(0, 5))

# Run BPfinder
shortbp_df = find_bp('short_introns.fa')
longbp_df = find_bp('long_introns.fa')

# Merge information from BP if using proximal or distal sites
longbp_df['bp_same'] = 1
longbp_df['ss_dist'] = longbp_df['ss_dist']-3
longbp_df = longbp_df[['seq_id', 'ss_dist', 'bp_seq', 'bp_same']]
mergebp_df = shortbp_df.merge(longbp_df, on=['seq_id', 'ss_dist', 'bp_seq'], how='left')
mergebp_df['bp_same'] = mergebp_df['bp_same'].fillna(0)

# Split the 'bp_seq' column into 9 separate columns
mergebp_df['bp_seq'] = mergebp_df['bp_seq'].str.upper()
bpsplit_df = mergebp_df["bp_seq"].apply(lambda x: pd.Series(list(x)))
# Rename the columns for clarity
bpsplit_df.columns = [f"bp_{i+1}_base" for i in range(9)]
# Merge back with the bp DataFrame
mergebp_df = pd.concat([mergebp_df, bpsplit_df], axis=1)

# Merge BP information to the data dataframe
data_df['seq_id'] = data_df.index.tolist()
data_df = data_df.merge(mergebp_df, how="left", on="seq_id")
data_df = data_df.drop(columns=['bp_seq', 'seq_id'])

data_df

,name,backbone,sequence complete,upstream exon,intron,downstream exon,NNAGNAG type,PSI ctrl. (s1),PSI ctrl. (s2),PSI ctrl. (s3),...,bp_same,bp_1_base,bp_2_base,bp_3_base,bp_4_base,bp_5_base,bp_6_base,bp_7_base,bp_8_base,bp_9_base
0,ppp1r12c CAGCAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,CCAGCAG,64.04,68.57,65.51,...,1,T,A,C,T,G,A,C,A,T
1,gpank1 CAGCAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,CCAGCAG,72.31,73.20,71.15,...,1,T,A,C,T,G,A,C,A,T
2,acin1 CAGCAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,ACAGCAG,65.57,71.78,67.65,...,1,T,A,C,T,G,A,C,A,T
3,ankrd11 AAGCAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,GAAGCAG,66.78,66.22,68.59,...,1,T,A,C,T,G,A,C,A,T
4,ppp1r12c CAGCAG,pcDNA3,GACGGATCGGGAGATCTCCCGATCCCCTATGGTGCACTCTCAGTAC...,AACCACCCCCTGCAGAACCCAGAACCCTCAATGGCGTCTCCTCCCC...,gtgagtggatgccctgagaggtcctgtgaggctgggagggcccgga...,CTTGAAGAGGCCCCCTTCTCCAGGCGCTTTGGCCTCCTGAAGACAG...,CCAGCAG,65.04,62.39,55.11,...,1,C,T,C,T,A,A,C,T,G
5,ppp1r12c UAGUAG,pcDNA3,GACGGATCGGGAGATCTCCCGATCCCCTATGGTGCACTCTCAGTAC...,AACCACCCCCTGCAGAACCCAGAACCCTCAATGGCGTCTCCTCCCC...,gtgagtggatgccctgagaggtcctgtgaggctgggagggcccgga...,CTTGAAGAGGCCCCCTTCTCCAGGCGCTTTGGCCTCCTGAAGACAG...,CTAGTAG,59.14,61.24,57.41,...,1,C,T,C,T,A,A,C,T,G
6,ppp1r12c CAGAAG,pcDNA3,GACGGATCGGGAGATCTCCCGATCCCCTATGGTGCACTCTCAGTAC...,AACCACCCCCTGCAGAACCCAGAACCCTCAATGGCGTCTCCTCCCC...,gtgagtggatgccctgagaggtcctgtgaggctgggagggcccgga...,CTTGAAGAGGCCCCCTTCTCCAGGCGCTTTGGCCTCCTGAAGACAG...,CCAGAAG,86.88,83.07,81.34,...,1,C,T,C,T,A,A,C,T,G
7,ppp1r12c AAGCAG,pcDNA3,GACGGATCGGGAGATCTCCCGATCCCCTATGGTGCACTCTCAGTAC...,AACCACCCCCTGCAGAACCCAGAACCCTCAATGGCGTCTCCTCCCC...,gtgagtggatgccctgagaggtcctgtgaggctgggagggcccgga...,CTTGAAGAGGCCCCCTTCTCCAGGCGCTTTGGCCTCCTGAAGACAG...,CAAGCAG,19.60,23.06,14.17,...,1,C,T,C,T,A,A,C,T,G
8,ppp1r12c UAGCAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,CTAGCAG,65.74,69.00,NaN,...,1,T,A,C,T,G,A,C,A,T
9,ppp1r12c CAGUAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,CCAGTAG,80.91,78.51,NaN,...,1,T,A,C,T,G,A,C,A,T
10,ppp1r12c AAGCAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,CAAGCAG,19.19,17.87,NaN,...,1,T,A,C,T,G,A,C,A,T
11,ppp1r12c CAGAAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,CCAGAAG,100.00,100.00,NaN,...,1,T,A,C,T,G,A,C,A,T
12,ppp1r12c GCAGCAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,GCAGCAG,100.00,99.73,NaN,...,1,T,A,C,T,G,A,C,A,T
13,ppp1r12c UCAGCAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,TCAGCAG,84.66,79.60,NaN,...,1,T,A,C,T,G,A,C,A,T
14,ppp1r12c AAAGCAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,AAAGCAG,60.32,55.80,NaN,...,1,T,A,C,T,G,A,C,A,T
15,ppp1r12c ACAGAAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,ACAGAAG,100.00,100.00,NaN,...,1,T,A,C,T,G,A,C,A,T
16,irf7 AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,CTGGAACCCGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGGA...,CTAGCAG,83.02,72.35,74.59,...,1,C,A,C,T,G,A,C,A,G
17,ocrl AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,GAGGACCTGGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGGA...,TTAGTAG,100.00,100.00,99.71,...,1,T,T,C,T,G,A,C,T,T
18,brca1 WT (?),GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,GAAGCAG,NaN,NaN,NaN,...,1,T,A,C,T,G,A,C,A,T
19,brca1 stop-gain,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,GAAGTAG,NaN,NaN,NaN,...,1,T,A,C,T,G,A,C,A,T
20,cftr stop-gain,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,TCAGTAG,NaN,NaN,NaN,...,1,T,A,C,T,G,A,C,A,T
21,scn8a AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,GTGGTGGTGAGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGG...,AAAGCAG,77.40,77.99,78.03,...,1,C,A,C,T,G,A,G,C,A
22,kcnq1 AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,CTTCCTCATCGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGG...,CTAGCAG,39.54,44.16,45.32,...,1,T,G,C,T,G,A,C,T,G
23,prpf8 AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,GGCCCTGTAGGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGG...,ATAGTAG,91.74,93.19,90.26,...,1,T,G,C,T,A,A,C,T,T
24,ccdc171 AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,GCTAAGAAGCGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGG...,TTAGAAG,100.00,100.00,100.00,...,1,A,C,G,T,G,A,C,C,T
25,ift172 AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,GAGCTGGAGGGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGG...,CCAGCAG,94.37,100.00,93.21,...,1,T,C,C,T,G,A,C,T,C
26,bltp1 AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,GTTGGTTCCTGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGG...,CTAGCAG,19.39,21.78,24.11,...,1,A,T,C,T,A,A,T,A,T
27,adck3 AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,TACCCTGGCGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGGA...,ACAGTAG,100.00,100.00,100.00,...,1,G,G,C,T,A,A,C,T,C
28,atrn AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,GACCATTCTTGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGG...,TCAGAAG,100.00,100.00,100.00,...,1,A,A,C,T,A,A,C,C,T
29,card9 AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,GTGTGCTCCTGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGG...,CCAGCAG,0.00,0.00,0.00,...,1,C,A,G,T,T,A,G,G,C
30,haghl AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,TTCGGGGCCAGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGG...,GCAGCAG,100.00,100.00,100.00,...,1,C,C,C,T,C,A,C,A,G
31,col11a2 AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,GAGCAGACAGGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGG...,TGAGAAG,5.52,2.48,1.16,...,1,C,C,C,T,A,A,C,A,T
32,dis3l2 stop-gain,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,CGAGTAG,NaN,NaN,NaN,...,1,T,A,C,T,G,A,C,A,T
33,fktn stop-gain,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,GTAGTAG,NaN,NaN,NaN,...,1,T,A,C,T,G,A,C,A,T
34,pkd1 stop-gain,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,TCAGTAG,NaN,NaN,NaN,...,1,T,A,C,T,G,A,C,A,T
35,scn1a stop-gain,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,ATAGTAG,NaN,NaN,NaN,...,1,T,A,C,T,G,A,C,A,T
36,vps13p stop-gain,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,CCAGTAG,NaN,NaN,NaN,...,1,T,A,C,T,G,A,C,A,T

##### 5. Adjust and save final dataframe

In [11]:
# Sequence related features adjustment
base_cols = [col for col in data_df.columns if col.endswith('_base')]
# Capitalize bases
data_df[base_cols] = data_df[base_cols].apply(lambda col: col.str.upper())
# Change T to U
data_df[base_cols] = data_df[base_cols].replace('T', 'U')

data_df

,name,backbone,sequence complete,upstream exon,intron,downstream exon,NNAGNAG type,PSI ctrl. (s1),PSI ctrl. (s2),PSI ctrl. (s3),...,bp_same,bp_1_base,bp_2_base,bp_3_base,bp_4_base,bp_5_base,bp_6_base,bp_7_base,bp_8_base,bp_9_base
0,ppp1r12c CAGCAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,CCAGCAG,64.04,68.57,65.51,...,1,U,A,C,U,G,A,C,A,U
1,gpank1 CAGCAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,CCAGCAG,72.31,73.20,71.15,...,1,U,A,C,U,G,A,C,A,U
2,acin1 CAGCAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,ACAGCAG,65.57,71.78,67.65,...,1,U,A,C,U,G,A,C,A,U
3,ankrd11 AAGCAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,GAAGCAG,66.78,66.22,68.59,...,1,U,A,C,U,G,A,C,A,U
4,ppp1r12c CAGCAG,pcDNA3,GACGGATCGGGAGATCTCCCGATCCCCTATGGTGCACTCTCAGTAC...,AACCACCCCCTGCAGAACCCAGAACCCTCAATGGCGTCTCCTCCCC...,gtgagtggatgccctgagaggtcctgtgaggctgggagggcccgga...,CTTGAAGAGGCCCCCTTCTCCAGGCGCTTTGGCCTCCTGAAGACAG...,CCAGCAG,65.04,62.39,55.11,...,1,C,U,C,U,A,A,C,U,G
5,ppp1r12c UAGUAG,pcDNA3,GACGGATCGGGAGATCTCCCGATCCCCTATGGTGCACTCTCAGTAC...,AACCACCCCCTGCAGAACCCAGAACCCTCAATGGCGTCTCCTCCCC...,gtgagtggatgccctgagaggtcctgtgaggctgggagggcccgga...,CTTGAAGAGGCCCCCTTCTCCAGGCGCTTTGGCCTCCTGAAGACAG...,CTAGTAG,59.14,61.24,57.41,...,1,C,U,C,U,A,A,C,U,G
6,ppp1r12c CAGAAG,pcDNA3,GACGGATCGGGAGATCTCCCGATCCCCTATGGTGCACTCTCAGTAC...,AACCACCCCCTGCAGAACCCAGAACCCTCAATGGCGTCTCCTCCCC...,gtgagtggatgccctgagaggtcctgtgaggctgggagggcccgga...,CTTGAAGAGGCCCCCTTCTCCAGGCGCTTTGGCCTCCTGAAGACAG...,CCAGAAG,86.88,83.07,81.34,...,1,C,U,C,U,A,A,C,U,G
7,ppp1r12c AAGCAG,pcDNA3,GACGGATCGGGAGATCTCCCGATCCCCTATGGTGCACTCTCAGTAC...,AACCACCCCCTGCAGAACCCAGAACCCTCAATGGCGTCTCCTCCCC...,gtgagtggatgccctgagaggtcctgtgaggctgggagggcccgga...,CTTGAAGAGGCCCCCTTCTCCAGGCGCTTTGGCCTCCTGAAGACAG...,CAAGCAG,19.60,23.06,14.17,...,1,C,U,C,U,A,A,C,U,G
8,ppp1r12c UAGCAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,CTAGCAG,65.74,69.00,NaN,...,1,U,A,C,U,G,A,C,A,U
9,ppp1r12c CAGUAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,CCAGTAG,80.91,78.51,NaN,...,1,U,A,C,U,G,A,C,A,U
10,ppp1r12c AAGCAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,CAAGCAG,19.19,17.87,NaN,...,1,U,A,C,U,G,A,C,A,U
11,ppp1r12c CAGAAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,CCAGAAG,100.00,100.00,NaN,...,1,U,A,C,U,G,A,C,A,U
12,ppp1r12c GCAGCAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,GCAGCAG,100.00,99.73,NaN,...,1,U,A,C,U,G,A,C,A,U
13,ppp1r12c UCAGCAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,TCAGCAG,84.66,79.60,NaN,...,1,U,A,C,U,G,A,C,A,U
14,ppp1r12c AAAGCAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,AAAGCAG,60.32,55.80,NaN,...,1,U,A,C,U,G,A,C,A,U
15,ppp1r12c ACAGAAG,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,ACAGAAG,100.00,100.00,NaN,...,1,U,A,C,U,G,A,C,A,U
16,irf7 AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,CTGGAACCCGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGGA...,CTAGCAG,83.02,72.35,74.59,...,1,C,A,C,U,G,A,C,A,G
17,ocrl AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,GAGGACCTGGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGGA...,TTAGTAG,100.00,100.00,99.71,...,1,U,U,C,U,G,A,C,U,U
18,brca1 WT (?),GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,GAAGCAG,NaN,NaN,NaN,...,1,U,A,C,U,G,A,C,A,U
19,brca1 stop-gain,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,GAAGTAG,NaN,NaN,NaN,...,1,U,A,C,U,G,A,C,A,U
20,cftr stop-gain,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,TCAGTAG,NaN,NaN,NaN,...,1,U,A,C,U,G,A,C,A,U
21,scn8a AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,GTGGTGGTGAGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGG...,AAAGCAG,77.40,77.99,78.03,...,1,C,A,C,U,G,A,G,C,A
22,kcnq1 AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,CTTCCTCATCGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGG...,CTAGCAG,39.54,44.16,45.32,...,1,U,G,C,U,G,A,C,U,G
23,prpf8 AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,GGCCCTGTAGGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGG...,ATAGTAG,91.74,93.19,90.26,...,1,U,G,C,U,A,A,C,U,U
24,ccdc171 AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,GCTAAGAAGCGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGG...,TTAGAAG,100.00,100.00,100.00,...,1,A,C,G,U,G,A,C,C,U
25,ift172 AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,GAGCTGGAGGGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGG...,CCAGCAG,94.37,100.00,93.21,...,1,U,C,C,U,G,A,C,U,C
26,bltp1 AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,GTTGGTTCCTGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGG...,CTAGCAG,19.39,21.78,24.11,...,1,A,U,C,U,A,A,U,A,U
27,adck3 AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,TACCCTGGCGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGGA...,ACAGTAG,100.00,100.00,100.00,...,1,G,G,C,U,A,A,C,U,C
28,atrn AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,GACCATTCTTGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGG...,TCAGAAG,100.00,100.00,100.00,...,1,A,A,C,U,A,A,C,C,U
29,card9 AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,GTGTGCTCCTGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGG...,CCAGCAG,0.00,0.00,0.00,...,1,C,A,G,U,U,A,G,G,C
30,haghl AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,TTCGGGGCCAGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGG...,GCAGCAG,100.00,100.00,100.00,...,1,C,C,C,U,C,A,C,A,G
31,col11a2 AG-gain,TWIST CMV RG6,TCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAA...,ATGGATTACAAGGATGACGATGACAAGGGGGTACCTGCCCCAAAAA...,gtaagtatcaacgcgttgcaagacaggtccaaggagaccaatagaa...,GAGCAGACAGGAGGTCAGGAGGATCCGGAGGACGAGGAGGAAGAGG...,TGAGAAG,5.52,2.48,1.16,...,1,C,C,C,U,A,A,C,A,U
32,dis3l2 stop-gain,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,CGAGTAG,NaN,NaN,NaN,...,1,U,A,C,U,G,A,C,A,U
33,fktn stop-gain,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,GTAGTAG,NaN,NaN,NaN,...,1,U,A,C,U,G,A,C,A,U
34,pkd1 stop-gain,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,TCAGTAG,NaN,NaN,NaN,...,1,U,A,C,U,G,A,C,A,U
35,scn1a stop-gain,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,ATAGTAG,NaN,NaN,NaN,...,1,U,A,C,U,G,A,C,A,U
36,vps13p stop-gain,GFPC1,TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCA...,ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCC...,gtaagtatcaacgcgttacaagacaggtttaaggagaccaatagaa...,GAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCG...,CCAGTAG,NaN,NaN,NaN,...,1,U,A,C,U,G,A,C,A,U

In [12]:
# Save the final dataframe to a new CSV file
data_df.to_csv(f"{OUTPUT_DIR}/{OUTPUT_PREFIX}_features.csv", index=False)